### PR TITLE
Remove usage of execinfo.h in spec tests

### PR DESCRIPTION
**Pull request by jbboehr**

### CODE REVIEW

**Comment by jbboehr** [comment]
cc @renoirb

**Comment by renoirb** [comment]
Thanks 📦 

We need a new release number :/

**Comment by jbboehr** [comment]
@renoirb Done.

**Comment by renoirb** [comment]
Can you do the same for the mustache PECL extension, please?  I'll update alpinelinux/aports Build manifesrs

**Comment by jbboehr** [comment]
@renoirb [Done](https://github.com/jbboehr/php-mustache/releases/tag/v0.7.3)

**Pull request merged**
